### ISSUE TITLE
初始化SQL

### ISSUE THREAD

**Issue by python8384** [yunnet/gardens#1]
hello，初始化SQL 是不是忘记push了？

**Comment by yunnet** [comment]
在https://github.com/yunnet/gardens/tree/master/doc 目录中

**Comment by heylel** [comment]
我只建了gdkxdl一个库，是不还要建立kxtimingdata这个数据库？我直接执行sql报错：在https://github.com/yunnet/gardens/tree/master/doc/kxtimingdata.sql这里有kxtimingdata.collect_base_info这个表，但是kxtimingdata这个库我没建立，可以把这里sql全改成gdkxdl吗
