### ISSUE TITLE
run erro---  gardens:runtime error: invalid memory address or nil pointer dereference ?

### ISSUE THREAD

**Issue by peteim** [yunnet/gardens#2]
gardens:runtime error: invalid memory address or nil pointer dereference  
stack:
D:/360极速浏览器下载/go1.10.3.windows-amd64/go/src/runtime/asm_amd64.s:573
D:/360极速浏览器下载/go1.10.3.windows-amd64/go/src/runtime/panic.go:502
D:/360极速浏览器下载/go1.10.3.windows-amd64/go/src/runtime/panic.go:63
D:/360极速浏览器下载/go1.10.3.windows-amd64/go/src/runtime/signal_windows.go:167
C:/Users/zhao/go/src/github.com/yunnet/gardens/controllers/HomeController.go:95
D:/360极速浏览器下载/go1.10.3.windows-amd64/go/src/runtime/asm_amd64.s:573
D:/360极速浏览器下载/go1.10.3.windows-amd64/go/src/reflect/value.go:447
D:/360极速浏览器下载/go1.10.3.windows-amd64/go/src/reflect/value.go:308
C:/Users/zhao/go/src/github.com/astaxie/beego/router.go:852
D:/360极速浏览器下载/go1.10.3.windows-amd64/go/src/net/http/server.go:2694
D:/360极速浏览器下载/go1.10.3.windows-amd64/go/src/net/http/server.go:1830
D:/360极速浏览器下载/go1.10.3.windows-amd64/go/src/runtime/asm_amd64.s:2361

**Comment by yunnet** [comment]
请检查一下你的go 的windows环境配置
